"""Creating subjects and professors_subjects tables

Revision ID: 03380bddfa30
Revises: ca3427b4127e
Create Date: 2020-09-01 01:56:31.822234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03380bddfa30'
down_revision = 'ca3427b4127e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Unicode(length=8), nullable=False),
    sa.Column('name', sa.Unicode(length=70), nullable=False),
    sa.Column('type', sa.Enum('mandatory', 'optional', name='subjecttypeenum'), nullable=False),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('drive_link', sa.Unicode(), nullable=True),
    sa.Column('whatsapp_link', sa.Unicode(), nullable=True),
    sa.Column('github_link', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('professors_subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'professor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professors_subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
