"""Creating lessons and professors_lessons tables

Revision ID: 883a2db3d291
Revises: 03380bddfa30
Create Date: 2020-09-01 01:57:33.225754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883a2db3d291'
down_revision = '03380bddfa30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=100), nullable=True),
    sa.Column('length', sa.Time(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professors_lessons',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'subject_id', 'professor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professors_lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
