"""Admin adjustments

Revision ID: 8a9b572cfa1c
Revises: 233af3faa7df
Create Date: 2020-09-04 03:39:29.530733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a9b572cfa1c'
down_revision = '233af3faa7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluations', 'period',
               existing_type=postgresql.ENUM('FIRST', 'SECOND', name='periodenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluations', 'period',
               existing_type=postgresql.ENUM('FIRST', 'SECOND', name='periodenum'),
               nullable=True)
    # ### end Alembic commands ###
