"""Adding column material_design_icon to subjects table

Revision ID: 937619cef753
Revises: fd57f64255da
Create Date: 2020-09-14 20:51:04.412674

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '937619cef753'
down_revision = 'fd57f64255da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('material_design_icon', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'material_design_icon')
    # ### end Alembic commands ###
