"""adding telegram_link to subjects table

Revision ID: b72c497938d8
Revises: da830b27bad5
Create Date: 2021-03-23 19:19:34.407414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72c497938d8'
down_revision = 'da830b27bad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('telegram_link', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'telegram_link')
    # ### end Alembic commands ###
