swagger: "2.0"
info:
  title: Sala de Estudos
  description: Sala de Estudos API documentation
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/v1"

paths:
  /subjects:
    get:
      operationId: sala_de_estudos_flask.ext.api.controllers.subjects_controller.list_all
      summary: Read the entire list of subjects
      description: Read the list of subjects
      responses:
        200:
          description: "Successful read subjects operation"
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Id of the subject
                code:
                  type: string
                  description: Code of the subject in the RNP servers
                name:
                  type: string
                  description: Name of the subject
                material_design_icon:
                  type: string
                  description: Material design icon to ilustrate de subject
